### ISSUE TITLE
Ordering of exercises in section 4

### ISSUE THREAD

**Issue by Phuong-Le** [cambiotraining/unix-shell#24]
In Section 4.7, after going through the previous exercises. When running 

```
rm backup/cubane.pdb
```

I got the following error "rm: backup/cubane.pdb: No such file or directory"

I assume the "Copy with multiple filenames" exercise should be placed before the "Wildcards" exercise for "backup/cubane.pdb" to be deletable? 

In other words, the current natural order to run code is

section 4.6 > "copy directories" exercise > section 4.7 > "wildcards" exercise > "Copy with multiple filenames" exercise

While it should be

section 4.6 > copy directories > "Copy with multiple filenames" exercise
 > section 4.7 > "wildcards" exercise 

Thankfully this should be a very quick fix (but if not fixed it can be quite confusing for students and new trainers)!

**Comment by tavareshugo** [comment]
Thanks @Phuong-Le! I think this is fixed now, I have changed the order of the exercises and linked the correct exercises to each section.
